apiVersion: v1
kind: ReplicationController
metadata:
  name: bmoapp
spec:
  replicas: 2
  selector:
    app: bmoapp
  template:
    metadata:
      name: bmoapp
      labels:
        app: bmoapp
    spec:
      containers:
        - name: bmocom
          image: myltech/tdrepo:1.2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bmoapp
spec:
  selector:
    app: bmoapp
  ports:
  - port: 8080
    targetPort: 8080
